# Generated by Django 4.0.6 on 2022-07-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='tbl_portfolio',
        ),
    ]
