# Generated by Django 4.0.6 on 2022-07-30 15:36

from django.db import migrations, models
import portfolio_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_portfolio_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, validators=[portfolio_app.custom_validators.validate_positive_number]),
        ),
    ]
