# Generated by Django 4.0.7 on 2022-08-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_portfolio_purchased_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='stock_symbol',
            field=models.CharField(max_length=200),
        ),
    ]
